package com.epam.mongo.domain;

public enum Command {
    LIST_ALL,
    LIST_OVERDUE,
    LIST_WITH_GIVEN_CATEGORY,
    LIST_SUBTASKS_WITH_GIVEN_CATEGORY,
    MANAGE_TASK,
    INSERT_TASK,
    UPDATE_TASK,
    DELETE_TASK,
    MANAGE_SUBTASK,
    INSERT_SUBTASK,
    UPDATE_SUBTASK,
    DELETE_SUBTASK,
    SEARCH_TASK,
    SEARCH_SUBTASK,
    EXIT
}
